### ISSUE TITLE
Unclear error "uploader on Google Play"

### ISSUE THREAD

**Issue by 3axapy** [onepf/AppDF#149]
Traceback (most recent call last):
  File "appdf.py", line 103, in <module>
    main()
  File "appdf.py", line 98, in main
    publisher.publish()
  File "/home/zakhar/IdeaProjects/AppDF/tools/uploader/lib/appdf/publishers/google_play.py", line 51, in publish
    self.add_languages()
  File "/home/zakhar/IdeaProjects/AppDF/tools/uploader/lib/appdf/publishers/google_play.py", line 143, in add_languages
    self.session.at_xpath(xpath).click()
AttributeError: 'NoneType' object has no attribute 'click'

**Comment by oorlov** [comment]
Hi @3axapy!

Google changes their developer console UI often, so we need to update AppDF publisher after it.
We are going to publish new version soon. You can try some fresh stuff from here
https://github.com/KapJI/AppDF/tree/master/tools/uploader
